### ISSUE TITLE
Riepilogo.... e errore per l'attivazione plugin Tags

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/HfcQGIS-md#1]
Buonasera :-)
Ho clonato il mio repo test di [HfcQGIS](https://github.com/gbvitrano/HfcQGIS_md) qui 
Personalizzando il template, ho attivato il cookie-law-popup e la barra di progressione della pagina, attivando queste due plugin il back to top di Material for MkDocs ha smesso di funzionare, probabilmente va in conflitto con il **jquery-3.1.1.min**, per cui ho installato altro back to top.

Non sono riuscito a far funzionare la [plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/) **Tags** natia di Material for MkDocs. La compilazione fallisce perchè la plugin non viene caricata. 
Va aggiunto un comando al file [requirements-mkdocs.txt](https://github.com/opendatasicilia/HfcQGIS-md/blob/main/requirements-mkdocs.txt)?

**Comment by aborruso** [comment]
Caro @gbvitrano , il plug-in tags non è da installare, ma soltanto da attivare `Note that no third-party plugin1 needs to be installed`.

Io ho aggiunto [solo questo](https://github.com/ondata/guidaVisiData/blob/master/mkdocs.yml#L20) e non ho avuto alcun problema di compilazione.

Posso fare qualche test in questo repo? Questo repo è la sorgente di RTD?

**Comment by aborruso** [comment]
@gbvitrano credo sia un plugin disponibile soltanto per chi finanzia il progetto 
![image](https://user-images.githubusercontent.com/30607/124443453-fcfcab80-dd7d-11eb-807f-5917beaf5eb5.png)

**Comment by gbvitrano** [comment]
capito

**Comment by gbvitrano** [comment]
se a te funziona significa che ondata a contribuito, visto che il repo e su ODS possiamo contribuire con una cifra una tantum o dobbiamo farlo ogni mese?

**Comment by aborruso** [comment]
> se a te funziona significa che ondata a contribuito, visto che il repo e su ODS possiamo contribuire con una cifra una tantum o dobbiamo farlo ogni mese?

No, non funzionava nemmeno a me, mi sbagliavo

**Comment by aborruso** [comment]
non applicabile
