### ISSUE TITLE
replicare n volte un file

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#10]
Nella sezione [variabili ](https://github.com/opendatasicilia/HfcQGIS-md/tree/main/docs/gr_funzioni/variabili)ci sono 130 variabili e quindi 130 nomi delle variabili elencate in questo file [elenco_variabili320.txt](https://raw.githubusercontent.com/opendatasicilia/HfcQGIS-md/main/docs/gr_funzioni/variabili/elenco_variabili320.txt).

Il mio goal è creare un file per ogni variabile e:

1. il nome del file deve essere il nome della variabile (*.md);
2. il contenuto dei file deve essere uguali per tutti, il file da copiare è [_file_tipo.md](https://raw.githubusercontent.com/opendatasicilia/HfcQGIS-md/main/docs/gr_funzioni/variabili/_file_tipo.md)

per far questo ho usato questo script:

```bash
#!/bin/bash
set -x

# crea loop
for i in $(cat elenco_variabili320.txt)
do
# crea file vuoto
	touch $i.md
# copia contenuto del file
	cp _file_tipo.md $i.md
done
```

sembra funzionare, ma è scritto bene?

**Comment by aborruso** [comment]
Se va bene, usalo.

In questi casi io uso una modalità alternativa:

```bash
<input.txt while read line; do
    echo "$line";
done
```

Legge ogni linea di input e lo associa alla variabile `line`.

Il ritorno a capo del file di input deve essere alla Linux, ovvero con Line Feed

**Comment by pigreco** [comment]
@aborruso grazie per il feedback

chiudo issue
