### ISSUE TITLE
Social Card per pagina singola

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/HfcQGIS-md#11]
Di default il sito ha la sua social card 
![hfc_social_new](https://user-images.githubusercontent.com/20488693/126769549-48dd3169-daa7-4ff0-939e-ee6cf803b7f0.png)

Adesso possiamo assegnare una social card ad ogni pagina/articolo del sito, ho inserito gli appositi blocchi in main.html

Aggiungere la social card alla singola pagina è semplicissimo, basta inserire il codice del meta tag nelle prime righe della pagina, come da esempio.

![2021-07-23_12h29_39](https://user-images.githubusercontent.com/20488693/126770011-7aaa6f2e-62d9-4949-a70f-f7cc74e99e87.png)
 `---
social_image: img/hfc_funz_geom.png
---`
`social_image:`  è comando che richiama in tag nel renderer html

`img `indica la cartella dove si trova l'immagine a prescindere dal livello del file dove viene inserito.

`hfc_funz_geom.png` è l'immagine che viene caricata. Se desideriamo immagine diverse per ogni pagina, l'immagine da caricare deve essere sempre diversa :-) 

Ecco un esempio don card di default e di pagina

 ## Twetter
![2021-07-23_12h13_16](https://user-images.githubusercontent.com/20488693/126770890-bba13c22-72fd-43a8-9015-b32f9da20873.png)
![2021-07-23_12h13_53](https://user-images.githubusercontent.com/20488693/126770903-32d5b30f-0a30-419c-93ab-7bf505183c06.png)
## Facebook
![2021-07-23_12h13_23](https://user-images.githubusercontent.com/20488693/126770941-60fbe980-1627-4af6-b948-b5c98cae5668.png)
![2021-07-23_12h14_01](https://user-images.githubusercontent.com/20488693/126770998-f8744d2f-e900-4541-a6a8-01ebcb3dcc97.png)

**Comment by pigreco** [comment]
wow, bello e utile

Ho realizzato una cartella `card_social` e all'interno ho messo le card in png, una per ogni gruppo.

Infine ho aggiunto, per ogni gruppo:

```
---
social_image: img/card_social/hfc_gr_GRUPPO.png
---
```
