### ISSUE TITLE
rendering immagini, non riesco a visualizzarle

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#13]
https://github.com/opendatasicilia/HfcQGIS-md/edit/main/docs/release/intro_novita.md

ho provato:

`img src="../img/splashscreen/splash_3_20.png"`

`img src="{{ config.site_url}}img/splashscreen/splash_3_20.png"`

mi arrendo :-(

EDIT: È codice HTML

**Comment by pigreco** [comment]
per adesso utilizzo il percorso assoluto:

`https://raw.githubusercontent.com/opendatasicilia/HfcQGIS-md/main/docs/img/splashscreen/splash_3_0_0.png`

ma mi piacerebbe capire come risolvere

**Comment by pigreco** [comment]
soluzione trovata da @gbvitrano 

```
img src="../../img/splashscreen/splash_3_20.png"
```

funziona

**Comment by aborruso** [comment]
Io la riaprirei, mi sembra che non funzioni: si sale due volte, quando la carella è soltanto un livello sopra.

Ed è brutto che l'anteprima in vscode non faccia vedere le immagini e il sito sì.

Credo che ci sia un errore babbo nel file di configuazione

**Comment by gbvitrano** [comment]
Non è una regola la mia. Ho applicato in base ai file.

**Comment by gbvitrano** [comment]
@aborruso il problema della visualizzazione con vscode potrebbe essere causato  dall"inserimento di codice html all"interno di un file md

**Comment by aborruso** [comment]
ciao @pigreco se usi l'HTML devi ragionare in ottica sito online, e sua struttura, non in md grezzo

La tua pagina è `https://hfcqgis-md.readthedocs.io/it/latest/release/intro_novita/`

Il file è [intro_novita.md](https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/release/), ma come sito è all'URL di sopra. Per arrivare alla cartella `img`, che è nella root, prima devi risalire in `release` e poi nella radice del sito, quindi devi salire due volte.

Sotto nella gif animata, vedi che rispetto a quel file, devo salire di due elementi gerarchici per arrivare a `img`.

![due](https://user-images.githubusercontent.com/30607/127007230-2fa5c974-8888-49a1-8cda-ff76ec239744.gif)

**Comment by pigreco** [comment]
@aborruso 
quindi sto usando un file .md, ma sto scrivendo codice html e quindi devo ragionare in html.

chiarissima la gif, grazie
