### ISSUE TITLE
richiesta di funzionalità: al clic aprire immagine per ingrandirla

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#15]
Una delle caratteristiche di #HfcQGIS è la ricchezza di screenshot, ma manca la possibilità di zoomarli.

È possibile aprire in un'altra scheda lo screenshot per poterlo zoomare a piacere?

grazie

**Comment by gbvitrano** [comment]
devo cercare un plugin e vedere se si adatta alle nostre esigenze

**Comment by gbvitrano** [comment]
Si può fare in  veloce veloce usando il css  `transform: scale(2);`
devo studiarci un pò

**Comment by gbvitrano** [comment]
Rieccomi, si può fare in diversi modi, ma cmq in qualsiasi caso devo creare nel css altre classi da applicare alle immagni.
attualmente alla classe `img` applico le regole per applicare il bordo e l'ombra, per creare l'evento al click vanno aggiunte altre regole che devono attivarsi al click del mouse.

Tutto questo significa che per applicare le nuove regole alle immagini che ti interessa ingrandire, le immagini devono essere necessariamente caricate con codice html in modo da assegnare la nuova azione al click del mouse.
Cosi la comodità del MD per caricare  le immagini svanisce.

Lunedì non sono a casa, martedì ti faccio un esempio per farmi capire meglio

**Comment by gbvitrano** [comment]
ho adattato uno script jquey il lavoro sporco lo fa lui, tu inserisci le immagini in md  :-)
meno invasivo di così non posso fare :-)
forse c'è margine di miglioramento nel css, ma per oggi mi fermo qui
 e vado a dormire  :-)
![2021-07-26_04h23_49](https://user-images.githubusercontent.com/20488693/126924646-5447a130-91ac-485b-92db-f06a90bc7def.png)

**Comment by gbvitrano** [comment]
vista di un classico monitor 19 pollici

![2021-07-26_04h28_40](https://user-images.githubusercontent.com/20488693/126924957-23c4dd47-cd8c-47f8-8fd5-447ef52dbb3d.png)

**Comment by pigreco** [comment]
Buongiorno,
la soluzione è perfetta ma nel mio laptop non funziona bene, la documento tramite questo video:


https://user-images.githubusercontent.com/7631137/126948249-b84c537b-af6a-4af7-9af7-c000dbf3b045.mp4

**Comment by pigreco** [comment]
aggiornamento:

ho provato con MS Edge, funziona bene!!!

**Comment by gbvitrano** [comment]
sto apportando alcune modifiche anche per il mobile, per questo adesso ti funziona meglio :-)

**Comment by gbvitrano** [comment]
adesso funziona meglio, più di così non posso forzare, è pur sempre un script adattato alle nostre esigenze,
adesso devo chiudere tutto :-)
ps. cancella la vecchia cronologia e prova a come funziona

**Comment by gbvitrano** [comment]
La dimensione delle immagini durante lo zoom dipende anche dalle dimensioni originali del file, per il futuro fai screenshot  preferibilmente tutti alle stesse dimensioni,  larghi almeno 1920px

**Comment by pigreco** [comment]
@gbvitrano 
ora funziona meglio anche in chrome

**Comment by gbvitrano** [comment]
Ho cambiato plugin per lo zoom sulle immagini, la disomogeneità delle dimensioni degli screenshot mi ha creato qualche problema per trovare una dimensione media che vada bene sempre.
Tu puoi continuare a fare gli screenshot come preferisci, ma nello zoom la dimensione massima è 800px, al limite per un classico 19 pollici o tablet accettabile per risoluzioni più alte. 

### risoluzione 1920 x1024 px
![2021-07-27_22h09_40](https://user-images.githubusercontent.com/20488693/127220695-3a56833c-cd0a-4df6-9932-826a017d8bbc.png)

### risoluzione 1280 x 1024 px
![2021-07-27_22h09_59](https://user-images.githubusercontent.com/20488693/127220703-1fb079d9-2e28-4127-b293-2d0dafeb839c.png)

**Comment by pigreco** [comment]
in questa immagine e chrome non funziona

https://hfcqgis-md.readthedocs.io/it/latest/calcolatore_campi/field_calc/#field-calc-rapido

**Comment by pigreco** [comment]
mi permetto un suggerimento, per zoomare le immagini farlo come qui (cliccate sull'immagine, si aprirà in una nuova scheda)

https://gis.stackexchange.com/questions/405032/how-do-i-split-string-in-field-calculator

**Comment by gbvitrano** [comment]
> in questa immagine e chrome non funziona
> 
> https://hfcqgis-md.readthedocs.io/it/latest/calcolatore_campi/field_calc/#field-calc-rapido
> 
> EDIT: ho notato che non funziona per immagini presenti a fine pagina

il popup a fine immagine viene aperto male, se uno clicca sull'immagine prima di arrivare al fondo si apre, ma non è normale che sia così.
al momento non ho una soluzione, usiamo un plugin nato per lavorare in condizioni diverse dalle nostre, posso solo rimettere il primo plugin che abbiamo usato.
![2021-07-28_15h42_49](https://user-images.githubusercontent.com/20488693/127332733-b9c058fe-7568-412a-b7cd-0f38d6b91afd.png)

**Comment by gbvitrano** [comment]
> mi permetto un suggerimento, per zoomare le immagini farlo come qui (cliccate sull'immagine, si aprirà in una nuova scheda)
> 
> https://gis.stackexchange.com/questions/405032/how-do-i-split-string-in-field-calculator

farlo come lì sarebbe facile in un cms tipo worldpresss o similari, che hanno plugin native per l'effetto zoom, in un semplice html la cosa è molto facile, qui dobbiamo adattare i vari plugin. 
Se hai pazienza, con calma posso fare una ricerca per capire se altri siti che usano lo stesso nostro template hanno integrato una plugin per zommare sulle immagini :-)

**Comment by pigreco** [comment]
@gbvitrano 
io non ho nessuna fretta, grazie :-)

**Comment by gbvitrano** [comment]
ho trovato questa issue https://github.com/squidfunk/mkdocs-material/issues/280
appena posso la studio :-)

**Comment by gbvitrano** [comment]
l'implementazione di lightbox è prevista in futuro :-) aspettiamo :-)n :-)

https://squidfunk.github.io/mkdocs-material/insiders/?h=lightbox#future

**Comment by gbvitrano** [comment]
Rieccomi... ho installato altra plugin... al contrario di quelle già provate, questa non fa il lavoro sporco per te... ma in compenso funziona bene e crea anche una galleria delle immagini che trova nella pagina.
qui un **[test](https://opendatasicilia.github.io/OpenDataSicilia-per-il-Coronavirus/Configurazione/conf1/)** 
dopo averla installata e configurata l'uso è molto semplice dai un'occhiata alla struttura di questo **[file](https://github.com/opendatasicilia/OpenDataSicilia-per-il-Coronavirus/blob/main/docs/Configurazione/conf1.md)**

Per funzionare correttamente ha bisogno di un'immagine target ed una big, tranquillo noi usiamo sempre la stessa.
quindi l'immagine deve aver un link a se stessa.
### esempio
`[![](../img/zone_rosse.png)](../img/zone_rosse.png)`

se ti piace il plugin non devi fare altro che modificare tutte le immagini che devono aprirsi in popup :-)

**Comment by pigreco** [comment]
@gbvitrano sei un genio

mi piace, lo proviamo sul gruppo Custom

**Comment by pigreco** [comment]
@gbvitrano 
per modificare tutti i link alle immagini per ogni gruppo funzione:

trova:
```
^(!\[\])(\(.+\))
```

sostituisci:
```
[$1$2]$2
```

qui un esempio:
https://regex101.com/r/IHrjVB/1

cc @aborruso (poi mi spiego meglio)

**Comment by pigreco** [comment]
modifica apportate usando regex:

```
trova: ^(!\[.+|\])(\(.+\))
sostituisci: [$1$2]$2
```

**Comment by pigreco** [comment]
ottima scelta quest'ultimo plugin, grazie @gbvitrano

**Comment by pigreco** [comment]
Solo per documentare:

È possibile risolvere il problema del `trova e sostituisci` su file diversi usando vscode:

![image](https://user-images.githubusercontent.com/7631137/127620916-ef8b034b-5ada-43b7-acec-6b09e8d5542d.png)

1. ricerca su intero repository
2. pattern regex come `trova`
3. pattern regex come `sostituisci`
4. cartella e file da includere
5. anteprima

fantastico
