### ISSUE TITLE
usare un grigio più chiaro nello sfondo degli esempi

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#16]
![image](https://user-images.githubusercontent.com/7631137/126909392-d8265d24-f436-43cd-a87f-6efd751f8e3e.png)

**Comment by gbvitrano** [comment]
Corretto

![2021-07-25_23h46_15](https://user-images.githubusercontent.com/20488693/126914451-77b4978e-cba3-4764-9205-89d5514549e6.png)

**Comment by pigreco** [comment]
buongiorno,
ottimo

chiudo issue
