### ISSUE TITLE
testo poco leggibile

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#18]
![image](https://user-images.githubusercontent.com/7631137/126948742-c4bc8df9-c034-4d11-8020-28b1c8112e64.png)

come ovviare?

**Comment by gbvitrano** [comment]
Basta ingrandire il testo 😊 e la regola viene applicata a tutto il sito. Quanto deve essere più grande?

**Comment by pigreco** [comment]
@gbvitrano siamo sicuri che è questione di 'grandezza' del testo?

io opterei per farlo in grassetto, cosi da vedersi meglio.

**Comment by gbvitrano** [comment]
La dimensione è rimasta invariata, ho aggiunto la proprietà che gestisce l'aspetto del testo, in questo caso è **grassetto**

![image](https://user-images.githubusercontent.com/20488693/127069215-c41de3ab-890f-43d3-931c-0fc83a964a10.png)

**Comment by pigreco** [comment]
@gbvitrano grazie

![image](https://user-images.githubusercontent.com/7631137/127107291-b331d3f6-41ed-4a62-8e32-2d75fd3a1cfb.png)
