### ISSUE TITLE
menu a destra non scorre

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#19]
nelle pagine con menu a destra e con menu abbastanza lungo da esserci una barra di scorrimento verticale, tale barra non scorre allo scorrere degli elementi e quando si supera l'altezza della patina il menu a destra non è più utile

(uso chrome)

allego per chiarezza un video (scusate l'audio)

https://user-images.githubusercontent.com/7631137/127040944-3dd504a9-8bc8-4afd-99b5-1558a555feaa.mp4

**Comment by gbvitrano** [comment]
Il menu credo che si nuove in modo indipendente dalla pagina centrale, prova a portare il cursore del morse sul menù di dx e controlla se scorre.

**Comment by gbvitrano** [comment]
Anche da mobile scorre in modo indipendente dalla pagina.
Nelle pagine corte  non si nota perché viene evidenziato il paragrafo, con la pagina lunga hai la sensazione che sia fermo, per verifica prova a guardare le guide suggerite da Andrea con le pagine lunghe

**Comment by pigreco** [comment]
@gbvitrano 
> prova a portare il cursore del mouse sul menù di dx e controlla se scorre.

sì, scorre se lo faccio manualmente.

Questo per me è un gran limite e ha poco senso, un vero peccato.

pazienza
