### ISSUE TITLE
applicare colore a una parola

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#2]
Per colorare di rosso una parola devo aggiungere prima della parola `_<span style="color:red;">` e dopo la parola `</span>_` ecco un esempio:

![image](https://user-images.githubusercontent.com/7631137/126062745-6ad6c713-a87d-4af2-9aef-8615a51ea9ab.png)

![image](https://user-images.githubusercontent.com/7631137/126062724-61f1b3a5-a8d6-45ab-9458-bd6253ab6644.png)

utilizzo AutoHotKey con due tasti diversi per aggiungere i due tag, esiste un modo per aggiungere velocemente e con unica combinazione di tasti i due tag?

lavoro su file `markdown`

**Comment by gbvitrano** [comment]
se applico una regola generale interveniamo su tutto il sito,
applicando la regola solo dove serve ottieni la sovrascrittura del css solo in quel punto
![image](https://user-images.githubusercontent.com/20488693/126063054-1a2d737e-57aa-4a27-b1cf-adb1ed14a4ed.png)

**Comment by pigreco** [comment]
grazie @gbvitrano 
chiudo issue
