### ISSUE TITLE
[script] modificare link immagini per molti file markdown

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#20]
Nel gruppo esempi sono presenti circa 50 file `*.md` che contengono link a immagini del tipo:

`![](../img/esempi/add_campo_sum_cum/sum_cum_01.png)`

o

`![pippo](../img/esempi/add_campo_sum_cum/sum_cum_01.png)`

che devo modificare in questo modo seguente, ovvero fare il link immagine di se stesso:

`[![](../img/esempi/add_campo_sum_cum/sum_cum_01.png)](../img/esempi/add_campo_sum_cum/sum_cum_01.png)`

per ottenere questa modifica ho usato il trova e sostituisci usando `regex`:

```
trova: ^(!\[.+|\])(\(.+\))
sostituisci: [$1$2]$2
```
ora dovrei creare uno script bash per automatizzare il tutto.

la cartella che contiene tutti i file `*.md` da modificare è: 

https://github.com/opendatasicilia/HfcQGIS-md/tree/main/docs/esempi

qui lista:
[lista_esempi.txt](https://github.com/opendatasicilia/HfcQGIS-md/files/6900615/lista_esempi.txt)

**Comment by pigreco** [comment]
Non ha molto senso perderci del tempo, sono solo 50 file.

Lo faccio manualmente.

**Comment by pigreco** [comment]
osservazione:

ci sono link di questo tipo (vedi sotto) che non devono essere presi:

![cucu](https://github.com/opendatasicilia/HfcQGIS-md/raw/main/docs/img/logo_hfc_2018.png)

**Comment by aborruso** [comment]
@pigreco prima di fare lo script, mi dai conferma che è questo quello che vuoi applicare?

https://regex101.com/r/bmKoPl/1

**Comment by pigreco** [comment]
> @pigreco prima di fare lo script, mi dai conferma che è questo quello che vuoi applicare?

esatto!

**Comment by aborruso** [comment]
@pigreco allora puoi usare un trova e sostituisci con `sed`

Attenzione che è distruttivo, modifica i file senza crearne copia.


```bash
#!/bin/bash

folder="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

set -x
set -e
set -u
set -o pipefail

for i in "$folder"/*.md; do
  sed -i -r 's/^(!)(\[.*?\])\(([^h].+)\)/[![](\3)](\3)/g' "$i"
done
```

**Comment by aborruso** [comment]
@picomiles nota: lo script è pensato per essere inserito nella stessa cartella in cui ci sono i file `md`

**Comment by pigreco** [comment]
ho fatto un test, funziona bene

grazie @aborruso
