### ISSUE TITLE
Inserire una pagina de per stumenti usati

### ISSUE THREAD

**Issue by gbvitrano** [opendatasicilia/HfcQGIS-md#21]
Buongiorno, 
si potrebbe inerire nella sezione **About** una pagina con gli strumenti/applicazioni usate per realizzare il sito.
qui un **[esempio](https://opendatasicilia.github.io/OpenDataSicilia-per-il-Coronavirus/strumenti/)**

**Comment by pigreco** [comment]
@gbvitrano buona idea, per me +1

**Comment by gbvitrano** [comment]
pagina inserita **[risorse](https://opendatasicilia.github.io/HfcQGIS-md/risorse/)**

**Comment by pigreco** [comment]
grazie @gbvitrano 

chiudo
