### ISSUE TITLE
inserire i nostri faccioni?

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#22]
secondo voi è una buona idea?

come qui:

https://fontanelle.ondata.it/#team

![image](https://user-images.githubusercontent.com/7631137/127650459-ff46cf97-53b9-4f94-86ec-8fcda279d080.png)

file è qui:  https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/img/probi_viri.png

**Comment by gbvitrano** [comment]
criceti inseriti :-)

https://opendatasicilia.github.io/HfcQGIS-md/ods/

**Comment by pigreco** [comment]
grazie @gbvitrano

**Comment by pigreco** [comment]
@gbvitrano posso spostare le foto nostre in una cartella `faccioni`, invece di lasciarle libere dentro la cartella docs/?

**Comment by pigreco** [comment]
@gbvitrano fatto!

**Comment by gbvitrano** [comment]
ok :-)
