### ISSUE TITLE
proposta: inserire una pagina sulle PR proposte e realizzate

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#24]
esempio:
- https://github.com/qgis/QGIS/pull/33437
- https://github.com/qgis/QGIS/issues/37544

**Comment by pigreco** [comment]
inserita

https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/pull-request.md

commenti?

**Comment by aborruso** [comment]
A me pare un lavoro oneroso da seguire bene.

Se tu, te la senti, fallo. Non rischia di diventare un paginone? Non potrebbe essere soltanto un elenco puntato con il titolo della PR (non necessariamente una traduzione, ma una frase che spiega di che si tratta) e il link alla PR?

Ovviamente soltanto PR correlate al field calculator

**Comment by pigreco** [comment]
@aborruso mi sono spiegato male.

alludo solo alle richieste di funzionalità fatte da me e non da tutta la comunità.

se vedi sono solo due e rimarranno tali per molto tempo.

grazie

**Comment by pigreco** [comment]
fatto!
