### ISSUE TITLE
indirizzo guida

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#27]
per adesso l'indirizzo della guida è questo:

```
https://hfcqgis-md.readthedocs.io/it/latest/
```

è previsto cambiarlo prima del lancio che avverà nei primi gliorni di settembre?

**Comment by gbvitrano** [comment]
L'indirizzo definitivo sarà sempre [http://hfcqgis.opendatasicilia.it/](http://hfcqgis.opendatasicilia.it/)
In questa nuova versione facciamo il render in html sia con RTD che direttamente con github.
Giocando con i miei test ho notato che spesso il domino settato su github dopo qualche compilazione spariva. Errore mio o bug? non saprei dire.
Per evitare sorprese direi di lasciare la renderizzazione su RDT visto che li non ha dato problemi con la vecchia versione.
Per lasciare tutto su RDT basta eliminare il vecchio progetto e impostare il dominio hfcqgis.opendatasicilia.it sul nuovo progetto.
Per evitare doppioni eliminerei anche le ghpages e il deploy automatico su github.

Per quanto riguarda il vecchi indirizzi e di conseguenza l'indicizzazione delle pagine con google, tramite la Google serch consolo posso facilmente cambiare la site map e nel giro di qualche settimana google riordina la ricerca.

**Comment by gbvitrano** [comment]
@pigreco cmq prima va pulito tutto, eliminare file .md superflui e collegamenti non più utili :-)
![2021-09-01_17h45_27](https://user-images.githubusercontent.com/20488693/131702431-8b1af62c-e088-4cbc-ab04-918bb2b8715e.png)

**Comment by pigreco** [comment]
> @pigreco cmq prima va pulito tutto, eliminare file .md superflui e collegamenti non più utili :-)

ci avevo pensato, ma è indispensabile?

intanto pulisco e faccio una copia, potrebbe essere utile in futuro.

**Comment by gbvitrano** [comment]
qui la nuova sitemap [sitemaps.zip](https://github.com/opendatasicilia/HfcQGIS-md/files/7092619/sitemaps.zip)

**Comment by pigreco** [comment]
@gbvitrano pulizia file mkdocs.yml fatta!

**Comment by gbvitrano** [comment]
> @gbvitrano pulizia file mkdocs.yml fatta!

e file .md? hai trasformato le funzioni in file unici, i singoli file si possono eliminare?

**Comment by gbvitrano** [comment]
> > @gbvitrano pulizia file mkdocs.yml fatta!
> 
> e file .md? hai trasformato le funzioni in file unici, i singoli file si possono eliminare?

mi correggo, hai già ripulito anche quelli, chiedo scusa :-)
