### ISSUE TITLE
il sito HfcQGIS-md mantenuto solo in github

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#29]
nella riunione del 4 settembre 2021, io e @gbvitrano, dopo valutazioni pro e contro, decidiamo:

1. di utilizzare la piattaforma GitHub per il nuovo sito HfcQGIS e non RTD;
2. cancellare il vecchio progetto HfcQGIS da RTD;
3. occorre intervento di @aborruso

**Comment by aborruso** [comment]
Buongiorno, allora farei così.

@pigreco guarda il sito da oggi in poi usando la versione github, che è già attiva a questo URL https://opendatasicilia.github.io/HfcQGIS-md/

Verifica che il sito sia ok, in termini di link, immagini (in modo spannometrico, navigando un po' da utente, facendo le varie cose che può fare un utente).

Se per te e @gbvitrano non ci sono problemi, posso fare tutto in serata,

**Comment by pigreco** [comment]
@aborruso 
il link https://opendatasicilia.github.io/HfcQGIS-md/ lo usiamo già da un po' e funziona tutto.

per me possiamo procedere, grazie

**Comment by aborruso** [comment]
ok, ho iniziato i lavori, per un po' ci potranno essere dei problemi
