### ISSUE TITLE
proposta: creare un menu di primo livello (orizzontale) "release"

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#3]
Per dare conto dei rilasci della guida nel tempo (uscirà fra poco la fantastica nuova), descrivere ognuna, dare i crediti a ognuna

**Comment by pigreco** [comment]
@aborruso 
io mi fido di te, anche se non ho capito la `fantastica nuova` :-)

**Comment by aborruso** [comment]
@pigreco la proposta è per te. La `fantastica nuova` è release. Che non ho scritto, perché in oggetto.

Non ti devi fidare. Se la proposta ti piace, appena puoi la devi implementare.

Altrimenti non si fa, non è importante.

**Comment by pigreco** [comment]
@aborruso 
hai un esempio da condividere?
 Le `release` sono relative a cosa? all'intera guida o alle `Novità` sulle nuove funzionalità del filed calc?

**Comment by aborruso** [comment]
> Per dare conto dei rilasci della guida

**Comment by pigreco** [comment]
@aborruso 
ottima idea
appena @gbvitrano è libero la implementiamo

grazie

**Comment by gbvitrano** [comment]
se non ho capito male oltre al **Novità** generale per QGIS va aggiunto un menu con le novità aggiunte in HfcQGIS

**Comment by pigreco** [comment]
> se non ho capito male oltre al **Novità** generale per QGIS va aggiunto un menu con le novità aggiunte in HfcQGIS

io non ho capito bene a cosa allude @aborruso , forse un menu che punti alla vecchia guida?

**Comment by aborruso** [comment]
@gbvitrano @pigreco io mi riferisco a una pagina, che illustra le edizioni di questa guida negli anni.
Questa guida è un prodotto, e non vi devo spiegare io cosa è la pagina release per un prodotto.

Con questa siamo alla seconda versione. Potrebbe finire in about.

Se la cosa non vi sembra utile, chiudete issue.

Grazie

**Comment by pigreco** [comment]
@aborruso ci provo a fare questo

# Release

In questa sezione ...

data         | release      | descrizione
-------------|--------------|-----------
luglio 2018  | #HfcQGIS v1  | Realizzato con RTD e [Sphinx Theme](https://github.com/rtfd/sphinx_rtd_theme)
luglio 2021  | #HfcQGIS v2  | Realizzato con RTD e tema [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)

**Comment by gbvitrano** [comment]
> @aborruso ci provo a fare questo
> 
> # Release
> In questa sezione ...
> 
> data	release	descrizione
> luglio 2018	#HfcQGIS v1	Realizzato con RTD e [Sphinx Theme](https://github.com/rtfd/sphinx_rtd_theme)
> luglio 2021	#HfcQGIS v2	Realizzato con RTD e tema [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)
> https://hfcqgis-md.readthedocs.io/it/latest/release/

molto bello, mi piace :-)

**Comment by pigreco** [comment]
> molto bello, mi piace :-)

le idee di @aborruso sono sempre chiare e belle! :-)

**Comment by aborruso** [comment]
@pigreco secondo me devi mettere in altro la più recente. Sono tutte così le sezioni release.

**Comment by pigreco** [comment]
@aborruso 

fatto, grazie
