### ISSUE TITLE
Correzione file di configurazione

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#31]
Ci sono diversi riferimenti a read the docs. Rimuoverli

**Comment by aborruso** [comment]
@gbvitrano ho fatto questo modifiche https://github.com/opendatasicilia/HfcQGIS-md/commit/96732697acf6438b8d4d9dbb11178fb2c68856bb

Fai per favore una verifica e se ok chiudi issue?

**Comment by gbvitrano** [comment]
Grazie
