### ISSUE TITLE
favicon poco visibili

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#32]
su monitor poco contrastati, è invisibile. Forse è meglio metterci, un "filo nero" attorno

![image](https://user-images.githubusercontent.com/30607/132131941-42ac15e2-7534-48c3-9107-25787bc631df.png)

**Comment by gbvitrano** [comment]
era nera e l'ho cambiata :-) ora la faccio verde :-)
![2021-09-05_17h45_07](https://user-images.githubusercontent.com/20488693/132132879-bf1cd9fe-a28d-4da8-92cb-57a54c9a17c2.png)

**Comment by aborruso** [comment]
era bianchiccia credo. Per questo dicevo di mettere un filo nero.

Ma fai tu :)

**Comment by gbvitrano** [comment]
l'avevo fatta bianca perché io uso il tema scuro e quindi non la vedevo :-)
come ti sembra cosi? 
![2021-09-05_18h12_10](https://user-images.githubusercontent.com/20488693/132133711-2aab9b80-6cde-457e-ac07-f84d8d2f9a8d.png)

**Comment by aborruso** [comment]
ok
