### ISSUE TITLE
Aprire la sezione discussions

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#33]
Potremmo aprire la sezione discussions, per ricevere domande sui temi della guida e per accettare proposte.

Mentre le issue soltanto per lavorare sul motore della guida (mkdocs) e sulla struttura.

**Comment by pigreco** [comment]
ok, provvedo :-)

**Comment by aborruso** [comment]
@pigreco non dimenticare di darne visibilità da qualche parte nel sito

**Comment by pigreco** [comment]
> @pigreco non dimenticare di darne visibilità da qualche parte nel sito

**Comment by pigreco** [comment]
@aborruso 
ho inserito indicazione per l'uso delle Discussions nella sezione contributing, ovvero Sostieni

https://hfcqgis.opendatasicilia.it/contributing/

grazie per le ottime idee
