### ISSUE TITLE
immagine non presente

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#35]
@pigreco in [questo file](https://raw.githubusercontent.com/opendatasicilia/HfcQGIS-md/main/docs/gr_funzioni/geometria/geometria_unico.md) si fa riferimento all'immagine `make_rectangle_3points2.png` che mi sembra non sia nel repo.

**Comment by gbvitrano** [comment]
anche nel vecchio repo manca l'immagine

**Comment by pigreco** [comment]
Lo screenshot manca e non ricordo cosa volesse rappresentare, quindi ho tolto il link
grazi
