### ISSUE TITLE
file svg non funziona

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#38]
@gbvitrano per caso hai una copia funzionante di questo file?

https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/img/hfc_funzioni.svg

non riesco ad aprilo in locale

**Comment by pigreco** [comment]
ovvero cerco il file svg con cui abbiamo generato le social card tipo questa:

![image](https://user-images.githubusercontent.com/7631137/133783161-12fa80f3-cf3d-4b68-934d-016ea05e657f.png)

**Comment by gbvitrano** [comment]
ho rifatto una base
[hfc_funzioni_gruppo_xxxxxx.zip](https://github.com/opendatasicilia/HfcQGIS-md/files/7187032/hfc_funzioni_gruppo_xxxxxx.zip)

**Comment by pigreco** [comment]
grazie mille @gbvitrano
