### ISSUE TITLE
cambiare tipo di carattere

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#4]
Il Carattere utilizzato da QGIS è Trueno:

https://www.qgis.org/en/site/getinvolved/styleguide.html#trueno-fonts

magari provare con Calibri

https://www.fontmirror.com/calibri

**Comment by gbvitrano** [comment]
Allo stato attuale il sito utilizza per la parte testuale il carattere **Lato** per i box  del codice **Roboto Mono** e vengono configurati nel **mkdocs.yml**

![image](https://user-images.githubusercontent.com/20488693/126297349-66085231-3a3e-4d54-92db-d98a0c8ba420.png)

invece per i vari menù il **Trueno**
![image](https://user-images.githubusercontent.com/20488693/126298237-1c220a94-c3c4-4a0d-995c-5d167721d5bd.png)

per fare prove puoi usare la libreria [google fonts](https://fonts.google.com/)

basta sostituire il carattere importato nel css **gbextra.css** 
e il **font-family** nelle vari sezioni dove sostituire il carattere

**Comment by gbvitrano** [comment]
se invece vuoi applicare lo stesso carattere a tutto il sito ti basta sostituirlo semplicemente nel **mkdocs.yml** e disattivare le regole che modificano il **font-family** nel file **gbextra.css**

**Comment by gbvitrano** [comment]
Pensavo che volevi fare delle prove tu :-) 
appena è tutto completo facciamo test per il carattere.
solo una domanda vuoi sostituire il carattere Trueno dei menù o  Lato per i box del codice Roboto Mono?
Vuoi un solo font per tutto il sito?

**Comment by pigreco** [comment]
> Vuoi un solo font per tutto il sito?

devo vedere per decidere e quindi occorre fare dei test

**Comment by pigreco** [comment]
@gbvitrano 

provo questo

https://fonts.google.com/specimen/Cutive+Mono

**Comment by gbvitrano** [comment]
giocare con il font lo farei alla fine, quando tutto è pronto, e le prove le farei in locale :-)

**Comment by pigreco** [comment]
boh, non cambia nulla
è inutile che faccia test io, dovrei studiare una marea di cose prima :-)

**Comment by gbvitrano** [comment]
li faccio io, ma a cose fatte, sembra una cretinata ma rubiamo tempo a tutto il resto del sito :-)

**Comment by gbvitrano** [comment]
ho sostituito con  Open Sans il font Lato del testo e il Trueno dei menù

**Comment by pigreco** [comment]
grazie @gbvitrano 

chiudo
