### ISSUE TITLE
Sostieni restituisce 404

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#44]
Buongiorno,
ho appena fatto click sulla barra verde in alto e ho

![image](https://user-images.githubusercontent.com/30607/141939240-c4eec272-fc2d-4028-9a4c-21c661c8ca45.png)

**Comment by pigreco** [comment]
Buongiorno @aborruso 
a me funziona:
cliccando sull abarra verde mi posta nella sezione `Sostieni`, se clicchi sula P su paypal

**Comment by aborruso** [comment]
![tt](https://user-images.githubusercontent.com/30607/141956146-d6c60e97-5705-489f-bd5d-cff7c82b8ecc.gif)

**Comment by pigreco** [comment]
@aborruso 
non so come aiutarti perché da me funziona

https://user-images.githubusercontent.com/7631137/141962179-f649b046-abb4-41f5-864b-6430a7312d4b.mp4

**Comment by gbvitrano** [comment]
![image](https://user-images.githubusercontent.com/20488693/141962794-257395aa-737d-4861-8366-6f16091cb9b3.png)

controllo, al primo click funziona, se per errore clicchi duo o più volte non trova la pagina, perchè il link sballa

**Comment by gbvitrano** [comment]
Risolto, ho scritto il link in modo diverso
Prima era 
`<a href="contributing/" class="nomobile" title="Contribuire a HfcQGIS" target="_parent"><strong>Se HfcQGIS ti è stato utile, valuta la possibilità di contribuire, leggi la sezione Sostieni</strong></a>` 

ora `<a href="{{ config.site_url}}contributing/" class="nomobile" title="Contribuire a HfcQGIS" target="_parent"><strong>Se HfcQGIS ti è stato utile, valuta la possibilità di contribuire, leggi la sezione Sostieni</strong></a>`

adesso al click,  in qualsiasi punto si trova,  va all'indirizzo `https://hfcqgis.opendatasicilia.it/contributing/`

**Comment by pigreco** [comment]
graize @aborruso per la segnalazione

grazie @gbvitrano per la risoluzione

chiudo
