### ISSUE TITLE
creare un calendario di HfcQGIS

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#46]
Creare un calendario con il logo di HfcQGIS e una esempio per ogni mese!!!

![logo_hfc_home21](https://user-images.githubusercontent.com/7631137/145690005-0a616e99-dc16-486f-945c-508dfe880d3b.png)

e metterlo a disposizione di tutti!!!

**Comment by gbvitrano** [comment]
metti screenshot di funzioni sexy...? :-) :-)

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/145690729-30bcff4b-b791-4b60-b527-5426169c19e6.png)

**Comment by aborruso** [comment]
Vale soltanto se l'hai creato con QGIS 👯
