### ISSUE TITLE
linea di separazione

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#5]
Nei paginoni utilizzo `---` per tracciare una linea di separazione:

![image](https://user-images.githubusercontent.com/7631137/126297734-fd5947e2-e1f6-450a-989b-47695cc2362c.png)

esiste un modo per farla più evidente?

**Comment by gbvitrano** [comment]
Per modificare la linea orizzontale **hr**

Devi aggiungere al codice css  gbextra.css
`.hr {border: 0; height: 1px; background:  #589632; background-image: linear-gradient(to right, #93b023,  #589632, #93b023);  width: 100%; margin: 20px 0;}	`

questa linea ha un gradiente verso l'esterno `background-image: linear-gradient(to right, #93b023,  #589632, #93b023); `
il come puoi notare ci sono tre colori uno principale (quello al centro) a dx e sx il colore delle sfumature

se non vuoi il gradiente di basta eliminare o spegnere la parte di codice.

esempio 1 parte di codice spento
`.hr {border: 0; height: 1px; background:  #589632; /*background-image: linear-gradient(to right, #93b023,  #589632, #93b023); */  width: 100%; margin: 20px 0;}	`

esempio 2 codice eliminato
`.hr {border: 0; height: 1px; background:  #589632;  width: 100%; margin: 20px 0;}	`

**Comment by pigreco** [comment]
@gbvitrano 

> Devi aggiungere al codice css gbextra.css
> `.hr {border: 0; height: 1px; background: #589632; background-image: linear-gradient(to right, #93b023, #589632, #93b023); width: 100%; margin: 20px 0;}`

non ha importanza dove metterlo? in qualsiasi riga?

**Comment by pigreco** [comment]
ho fatto così:

![image](https://user-images.githubusercontent.com/7631137/126312803-68e4e5f6-118c-4f5d-8c46-af0802a5ba5b.png)

**Comment by pigreco** [comment]
@gbvitrano @aborruso 

ho aggiunto il codice ma non vedo nessuna differenza.

https://github.com/opendatasicilia/HfcQGIS-md/blob/06e54580badbd2359a9301bf817a0bdaba41dcf6/docs/stylesheets/gbextra.css#L273

![image](https://user-images.githubusercontent.com/7631137/126363729-936774bd-908a-4d89-80ee-c7d582373b69.png)

**Comment by gbvitrano** [comment]
adesso funziona ho forzato anche la regola  **.md-typeset hr**

![image](https://user-images.githubusercontent.com/20488693/126451331-f8fa7e3e-7c09-49bc-88a7-addc4bdb738e.png)

**Comment by pigreco** [comment]
grazie  @gbvitrano , ora è OK!
