### ISSUE TITLE
HfcQGIS tramite me è sponsor di QGIS.org

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#51]
come fare comparire la cosa nel sito?

https://github.com/sponsors/qgis

![image](https://user-images.githubusercontent.com/7631137/152643797-2a78adac-8d62-4e04-a59e-e2af18d1ead3.png)

**Comment by gbvitrano** [comment]
<a href="https://hfcqgis.opendatasicilia.it/autore/#sponsor-qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=sponsor%20by&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Sponsor QGIS"></a>

```
<a href="https://hfcqgis.opendatasicilia.it/autore/#sponsor-qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=sponsor%20by&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Sponsor QGIS"></a>
```

**Comment by pigreco** [comment]
alla fine ho utilizzato questo, grazie @gbvitrano 

<a href="https://github.com/sponsors/qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=sponsor%20by&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Sponsor QGIS"></a>

```
<a href="https://github.com/sponsors/qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=sponsor%20by&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Sponsor QGIS"></a>
```

cambia solo il link di arrivo :-)

**Comment by pigreco** [comment]
<a href="https://github.com/sponsors/qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=Supporting&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Supporting QGIS"></a>


```
<a href="https://github.com/sponsors/qgis" target="_blank"><img src="https://img.shields.io/static/v1?label=Supporting&message=QGIS&color=ff9900&logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAABkUlEQVQ4ja2Sv0tbURTHv/e+e5/68kIgi2gWETu5CHXrGAiNEezaQRBdBdHB/gc6Cf4DIdBFKHQITdI8p0IlIJTi0i4BURDX5JH7ou+9+8MlYkxJiMXPdDjf8zmHCxd4TUyxmDSl0uTQvFSaNMVisr9HACCu1d4R1z2gtr0MrSMt5W8IccxWVr4BgPS8D3CcHcr5EozhOorOtRCf7ELhFzGelzCue0EcZ+HZNSm70vd3oZTF0ukjwthUf66D4A9tNpdZbFlbfEAGAMKYw5LJw149NZjTRGIxzmQ2GGFsbtibiW2nh2W9/A1FGIajhkYSxxFFHNeMlPcvlrVWpNs9o3x19afudE5e6qtO5ztbW6tSALCur/eUEGfjyiaKLpUQ+0DvHwDAfaUyz1OpL9R1346Uw/BGtVrrPJ//8WwBAASnp7MTnH+2UqksCPlH1kHwV/n+pl0onD/2aP9AIpe7tYD3st0+NEpFT6Y2qt3+euf72X55JLJa/agbjaZuNK6ien17LGkQUS5PB/X6zH/J4/IAd1+kpmPB/IUAAAAASUVORK5CYII=&logoColor=ff9900&style=for-the-badge" title="Supporting QGIS"></a>
```

usato questo alla fine!
