### ISSUE TITLE
attivare i tag

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#52]
sembra che i tag sono disponibili per tutti:

https://twitter.com/squidfunk/status/1494207813232607234

https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tag#usage

**Comment by aborruso** [comment]
Lo sono adesso, che ha rilasciato la 8.2 https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.0

Quindi da ora sono usabili

**Comment by gbvitrano** [comment]
In locale ho aggiornato la versione di [Material for MkDocs ](https://squidfunk.github.io/mkdocs-material/) e si è rotto **Mermaid diagrams** si devono aggiornare?

![2022-02-17_18h26_51](https://user-images.githubusercontent.com/20488693/154538506-cac91a94-0f7d-4b8e-a31e-ce2e6516340e.png)

**Comment by aborruso** [comment]
Fatto https://github.com/opendatasicilia/HfcQGIS-md/commit/13ed449aad3eec09a5bfa4d1390c9fd926f19307

**Comment by gbvitrano** [comment]
che meraviglia :-)
![2022-02-17_19h32_24](https://user-images.githubusercontent.com/20488693/154547887-093dd481-bba2-49ee-b4d9-0e0d2aba4ebf.png)
