### ISSUE TITLE
proposta: aggiungere sezione "webmaster" in about

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#6]
Ciao, il lavoro fatto da Gianni è proprio tanto.

Secondo me merita una sezione in about. Come nome mi viene "webmaster", ma magari ce ne è di meglio

**Comment by pigreco** [comment]
Ottima idea, per me va benissimo!

**Comment by pigreco** [comment]
https://hfcqgis-md.readthedocs.io/it/latest/webmaster/gbvitrano/

**Comment by pigreco** [comment]
https://hfcqgis-md.readthedocs.io/it/latest/webmaster/gbvitrano/

**Comment by gbvitrano** [comment]
Grazie :-)

**Comment by aborruso** [comment]
Io però la metterei in about

Scegliete voi

______
Scusami per la brevità, ti sto scrivendo dal cellulare.

website: https://medium.com/tantotanto
38° 7' 48" N, 13° 21' 9" E EPSG:4326

Il ven 23 lug 2021, 12:20 Giovan Battista Vitrano ***@***.***>
ha scritto:

**Comment by pigreco** [comment]
> Io però la metterei in about

è già in About
![image](https://user-images.githubusercontent.com/7631137/126774635-d5acf332-d80f-4e71-a3f0-f460ca13b14e.png)

**Comment by aborruso** [comment]
@pigreco era nel menu orizzontale in alto. Ora non più, è ok
