### ISSUE TITLE
come creare liste con rientri

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#7]
Parto da questa https://hfcqgis-md.readthedocs.io/it/latest/gr_funzioni/aggrega/aggrega_unico/#aggregate

```
Argomenti:

- *<span style="color:red;">layer</span>* una stringa, rappresentante o un nome di un layer o un ID di layer
- *<span style="color:red;">aggregate</span>* una stringa corrispondente all'aggregato da calcolare. Opzioni valide sono:

  - count
  - count_distinct
  - count_missing
  - min
  - max
  - sum
  - mean
  ```

e vorrei visualizzare, da `count` in poi, un elenco rientrato e non all'ineato come visibile sotto:

![image](https://user-images.githubusercontent.com/7631137/126637804-d13c7fc9-c640-445e-9d2d-295378708f51.png)

nonostante abbia seguito questo https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists, l'allineamento è sempre quello non desiderato.

**Comment by aborruso** [comment]
ciao totò, forse non ho capito. Ti direi di scrivere così (4 spazi)

```
- uno
- due
    - count
    - count_distinct
    - count_missing
    - min
    - max
    - sum
    - mean
```

E viene così

- uno
- due
    - count
    - count_distinct
    - count_missing
    - min
    - max
    - sum
    - mean

**Comment by pigreco** [comment]
@aborruso 
ottimo, erano 4 spazi, io ne davo solo due

funziona:

![image](https://user-images.githubusercontent.com/7631137/126649882-229a86d5-96f7-4436-81f5-41bf611de474.png)

grazie :-)

**Comment by pigreco** [comment]
alcune volte il tasto tab della tastiera applica 2 spazi altre volte 4, mistero :-(
