### ISSUE TITLE
cookie consent

### ISSUE THREAD

**Issue by dennisangemi** [opendatasicilia/HfcQGIS-md#73]
Ciao a tutti! Material for mkdocs ha rilasciato la possibilità di attivare cookie consent nativamente https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#native-cookie-consent

forse è il caso di sostituire il messaggio attuale?
![image](https://user-images.githubusercontent.com/77018886/181237979-fd64ccd9-c649-495b-914c-42a7e6fb6bbf.png)

p.s.
farei una PR ma ho provato ad abilitare i cookie consent [in un altro sito ](https://github.com/UNICT-DMI/DFA-compiti/blob/9c5796a2c359fdcad3491b0ae8a60ebf4a72501f/mkdocs.yml#L19)e non sono stato in grado lol

**Comment by gbvitrano** [comment]
grazie @dennisangemi, appena posso mi studio la novità e faccio la modifica

**Comment by gbvitrano** [comment]
Scusate ma non l'avevo vista, non sto molto al pc in questo periodo
![2022-09-25_22h20_36](https://user-images.githubusercontent.com/20488693/192163644-1fc59c96-76e8-4da9-a5d7-8c92739907ac.png)

**Comment by dennisangemi** [comment]
Fighissima @gbvitrano ! Chiudo, grazie ;)
