### ISSUE TITLE
mancano pezzi di descrizione nelle funzioni

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#74]
ho notato qualcosa di strano in #HfcQGIS
qui, nel repo github è corretto: https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/gr_funzioni/geometria/geometria_unico.md#overlay_intersects

leggo:

Sintassi <= QGIS 3.22.x

e

Sintassi >= QGIS 3.24.x

ecco screenshot:

![image](https://user-images.githubusercontent.com/7631137/183424777-cafdb06c-27c2-4669-b2c2-d4ebc85d169a.png)

qui, nel sito mancano pezzi di testo: https://hfcqgis.opendatasicilia.it/gr_funzioni/geometria/geometria_unico_con_troppi_colori/#overlay_intersects

ecco screenshot:

![image](https://user-images.githubusercontent.com/7631137/183424809-bf25cab1-cc84-4036-b823-61082fb4ee6b.png)

come se non si aggiornasse o puntasse ad altro file

**Comment by aborruso** [comment]
@pigreco c'è qualcosa che sicuramente sbaglio. 

Ho aperto la [pagina](https://github.com/opendatasicilia/HfcQGIS-md/blob/main/docs/gr_funzioni/geometria/geometria_unico_con_troppi_colori.md#overlay_intersects), e anche nel repo non vedo le parti che mancano


![image](https://user-images.githubusercontent.com/30607/183431402-223f80b4-9ca7-4d85-a484-825a672cfd12.png)

**Comment by aborruso** [comment]
@pigreco hai due pagine, che non ho capito se sono diverse `geometria_unico` e `geometria_unico_con_troppi_colori`

- https://hfcqgis.opendatasicilia.it/gr_funzioni/geometria/geometria_unico/#overlay_intersects
- https://hfcqgis.opendatasicilia.it/gr_funzioni/geometria/geometria_unico_con_troppi_colori/#overlay_intersects

Una delle due ha il testo che vuoi, perché lo contiene, e l'altra no, perché non lo contiene.
