### ISSUE TITLE
Dati scaricabili errati

### ISSUE THREAD

**Issue by MassimilianoVi** [opendatasicilia/HfcQGIS-md#77]
Buongiorno, seguendo la guida https://hfcqgis.opendatasicilia.it/esempi/distanze_progressive_chilometriche/?fbclid=IwAR0ekPQ7znWtgjPRrr2shp3wuTWPQ1yS5MQmSoZo34ayixmJwzx-Jm226sM#prova-tu, i dati non li trovo. trovo solo. Si scarica solamente un file "rotazione pattern lineare.zip", che non centra niente con quanto descritto nell'esercizio.

**Comment by pigreco** [comment]
Buongiorno e grazie per la segnalazione.

Ho appena sistemato il link, ora punta alla cartella corretta.

https://github.com/opendatasicilia/HfcQGIS-md/raw/main/docs/prova_tu/dati_progetto_dist_progr.zip
