### ISSUE TITLE
cambia il carattere in MS EDGE

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#78]
![image](https://user-images.githubusercontent.com/7631137/222793620-a6e4162b-4960-4da5-b088-90e40a60fd30.png)

**Comment by pigreco** [comment]
Aggiungo altre info:

l'immagine è nella prima [pagina ](https://hfcqgis.opendatasicilia.it/)del sito e su desktop

![image](https://user-images.githubusercontent.com/7631137/222801144-8551487d-7333-40d5-84ec-0ac1035c3dd1.png)

**Comment by pigreco** [comment]
che strano
nel mio PC il locale funziona bene anche su EDGE:
![image](https://user-images.githubusercontent.com/7631137/222801407-0cd820cb-8919-4a1a-9ea8-3ab75c7aa47a.png)

**Comment by gbvitrano** [comment]
e cosi a schermo intero
![2023-03-03_19h41_40](https://user-images.githubusercontent.com/20488693/222801561-9a388c25-b14f-4182-8ea4-8b361d5ec195.png)

**Comment by pigreco** [comment]
ok, @gbvitrano 
si verifica solo nel mio PC aziendale in VPN che si trova a Bari

chiudo, forse il PC aziendale ha delle limitazioni strane

scusate il rumore

grazie

**Comment by gbvitrano** [comment]
> ok, @gbvitrano si verifica solo nel mio PC aziendale in VPN che si trova a Bari
> 
> chiudo, forse il PC aziendale ha delle limitazioni strane
> 
> scusate il rumore
> 
> grazie
 non chiudere, magari noi abbiamo il font installato e si vede bene, nel pc aziendale no, ora converto il file svg in png cosi si vede bene ovunque :-)

**Comment by gbvitrano** [comment]
Logo modificato in png, adesso si dovrebbe visualizzare bene in tutti i pc
