### ISSUE TITLE
elenco puntato renderizzato male nel blog

### ISSUE THREAD

**Issue by pigreco** [opendatasicilia/HfcQGIS-md#84]
Ho scritto altro bloc con un elenco puntato: 
![image](https://github.com/opendatasicilia/HfcQGIS-md/assets/7631137/81d7a1af-ce9f-4c94-b174-8fb102ba30d9)

nel blog lo vedo così:
![image](https://github.com/opendatasicilia/HfcQGIS-md/assets/7631137/44570a7c-81b1-4e3c-837f-2b96b4c71b51)

https://hfcqgis.opendatasicilia.it/blog/2023/09/25/help-in-linea/

**Comment by pigreco** [comment]
occorre lasciare una riga vuota

grazie @cirospat

**Comment by gbvitrano** [comment]
1. definizione della funzione:   
	1. la definizione è indispensabile perché fa capire cosa fa e cosa non fa la funzione in oggetto;
	2. alcune volte ha, nel testo, dei rimandi che spiegano ulteriormente l'uso della funzione;

Ecco comew
Ecco come deve essere l'elenco puntato con all'interno un elenco secondario
2. sintassi:   
	1. spiega come usare la funzione stessa tramite gli argomenti il cui ordine è findamentale;
	2. i parametri denominati permettono di alterare l'ordine degli argomenti e rendere più leggibile le espressioni;
	3. indica gli argometi obligatori e quelli opzionali;
   
3. argomenti:   
	1. alcune funzioni non hanno argomenti, come per esempio quelle funzioni geometriche che iniziono per $;
	2. altre funzioni hanno molti argomenti, ma non tutti sono obligatori;
   
4. esempi:   
	1. ci sono esempi che spiegano come va usata la funzione;
	2. spesso ci sono più di un esempio in cui vengono usate i vari argomenti.

**Comment by gbvitrano** [comment]
![2023-09-25_14h18_19](https://github.com/opendatasicilia/HfcQGIS-md/assets/20488693/7c47dcff-7a79-4ee1-81ed-36aafe34d5ee)
