### ISSUE TITLE
proposta: dare evidenza alle donazioni per sostenere la guida

### ISSUE THREAD

**Issue by aborruso** [opendatasicilia/HfcQGIS-md#9]
Ciao,
deve essere più evidente. Idee:

- mettere nel menu in alto "Sostieni";
- mettere nei tastini nel footer il logo paypal

Ci possono essere mille altri modi. Però si deve vedere di più

**Comment by pigreco** [comment]
Ho spostato `Contribuisci a HfcQGIS` nel menu in alto, messo subito dopo 'Lavora con Noi` e prima di `About`

![image](https://user-images.githubusercontent.com/7631137/126868593-8c2630b7-b7e8-4399-aabb-0c2430173764.png)

https://hfcqgis-md.readthedocs.io/it/latest/contributing/

**Comment by pigreco** [comment]
per il secondo punto, logo Paypal occorre @gbvitrano :-)

**Comment by gbvitrano** [comment]
Aggiunta icona paypal

![image](https://user-images.githubusercontent.com/20488693/126894600-40257f78-b374-4c20-988d-90619156e1ae.png)

**Comment by pigreco** [comment]
@gbvitrano 
non sarebbe meglio mettere il link: `https://www.paypal.com/paypalme/pigrecoinfinito` ?

**Comment by gbvitrano** [comment]
provvedo :-)
